name = "cloudflare-playwright"
main = "src/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-05"
upload_source_maps = true

[browser]
binding = "MYBROWSER"

# KV存储配置用于保存登录信息
[[kv_namespaces]]
binding = "WEIBO_KV"
id = "711dc4835b0c471bae64f698c2e14796"  # 需要替换为实际的KV namespace ID
preview_id = "711dc4835b0c471bae64f698c2e14796"  # 需要替换为预览环境的KV namespace ID
